#!/usr/bin/env python3
"""
tools/train_difficulty_predictor.py

Train a gradient-boosted classifier on the instance difficulty dataset and
export the model as a self-contained C++ header with zero runtime dependency.

Difficulty tiers (from generate_training_data.py):
  "easy"   — heuristic gap to exact < 1%
  "medium" — gap 1–10%
  "hard"   — gap > 10%, or exact intractable (N > 6)

Usage:
    python3 tools/train_difficulty_predictor.py [--data tools/difficulty_data.csv]
                                               [--out  lib/heuristics/auto/difficulty_predictor.hpp]
                                               [--depth 6] [--trees 150]
"""

import argparse
import os
from collections import Counter

import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report
from sklearn.tree import _tree

FEATURE_NAMES = ["N", "memoryRatio", "hasStartups", "hasCommCost",
                 "heteroA", "heteroC", "heteroS", "startupFraction",
                 "hasBeta", "hasCost",
                 "meanA", "meanC", "meanS", "speedupA", "speedupC", "loadPerProc"]

DIFFICULTY_ORDER = ["easy", "medium", "hard"]   # ascending difficulty


# ── CSV load ───────────────────────────────────────────────────────────────

def load_data(path):
    import csv
    rows = []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            features = [float(row[n]) for n in FEATURE_NAMES]
            rows.append((features, row["difficulty"]))
    X = np.array([r[0] for r in rows])
    y = np.array([r[1] for r in rows])
    return X, y


# ── export GBM as a score-accumulating C++ function ───────────────────────

def gbm_to_cpp(model, feature_names):
    classes   = list(model.classes_)
    n_classes = len(classes)
    all_trees = []
    for stage in model.estimators_:
        for cls_idx, tree in enumerate(stage):
            all_trees.append((cls_idx, tree.tree_))

    lines = []
    lines.append("// Auto-generated by tools/train_difficulty_predictor.py — do not edit.")
    lines.append("// Gradient-boosted ensemble exported as a score-accumulating C++ function.")
    lines.append(f"// {len(model.estimators_)} stages × {n_classes} classes = "
                 f"{len(all_trees)} trees total.")
    lines.append(f"// Feature order: {', '.join(feature_names)}")
    lines.append("")
    lines.append(f"static constexpr int kDiffNumClasses  = {n_classes};")
    lines.append(f"static constexpr int kDiffNumFeatures = {len(feature_names)};")
    lines.append("")
    lines.append("static constexpr const char* kDifficultyNames[] = {")
    for cls in classes:
        lines.append(f'    "{cls}",')
    lines.append("};")
    lines.append("")
    lines.append("static void accumulate_diff_scores(const float* f, double* scores) {")
    lines.append(f"    // {len(all_trees)} decision trees")

    for stage_i, stage in enumerate(model.estimators_):
        for cls_idx, est in enumerate(stage):
            t = est.tree_
            lines.append(f"    // stage {stage_i}, class {cls_idx} ({classes[cls_idx]})")

            def recurse(node, depth):
                pad = "    " * (depth + 1)
                if t.feature[node] != _tree.TREE_UNDEFINED:
                    fi  = t.feature[node]
                    thr = t.threshold[node]
                    lines.append(f"{pad}if (f[{fi}] <= {thr:.10f}f) {{")
                    recurse(t.children_left[node],  depth + 1)
                    lines.append(f"{pad}}} else {{")
                    recurse(t.children_right[node], depth + 1)
                    lines.append(f"{pad}}}")
                else:
                    val = t.value[node][0][0]
                    lines.append(f"{pad}scores[{cls_idx}] += {val:.10f};")

            recurse(0, 0)

    lines.append("}")
    return lines, classes


# ── main ──────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data",  default=os.path.join(os.path.dirname(__file__), "difficulty_data.csv"))
    ap.add_argument("--out",   default=os.path.join(os.path.dirname(__file__),
                                                     "..", "lib", "heuristics", "auto",
                                                     "difficulty_predictor.hpp"))
    ap.add_argument("--depth", type=int, default=6,   help="max tree depth")
    ap.add_argument("--trees", type=int, default=150, help="number of boosting stages")
    ap.add_argument("--seed",  type=int, default=0)
    args = ap.parse_args()

    print(f"Loading {args.data} ...")
    X, y = load_data(args.data)
    print(f"  {len(X)} samples, classes: {sorted(set(y))}")

    dist = Counter(y)
    print("  Label distribution:")
    for label, count in sorted(dist.items(), key=lambda x: DIFFICULTY_ORDER.index(x[0])):
        print(f"    {label:10s} {count:6d}  ({100*count/len(y):.1f}%)")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.15, random_state=args.seed, stratify=y)

    print(f"\nTraining GradientBoostingClassifier "
          f"(depth={args.depth}, trees={args.trees}) ...")
    model = GradientBoostingClassifier(
        n_estimators=args.trees,
        max_depth=args.depth,
        learning_rate=0.1,
        subsample=0.8,
        random_state=args.seed,
        verbose=0,
    )
    model.fit(X_train, y_train)

    acc = model.score(X_test, y_test)
    print(f"  Test accuracy: {acc:.3f}")
    print("\nClassification report:")
    print(classification_report(y_test, model.predict(X_test),
                                target_names=sorted(set(y))))

    cv_scores = cross_val_score(model, X, y, cv=5)
    print(f"5-fold CV accuracy: {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")

    print("\nFeature importances:")
    for name, imp in sorted(zip(FEATURE_NAMES, model.feature_importances_),
                            key=lambda x: -x[1]):
        bar = "█" * int(imp * 40)
        print(f"  {name:20s} {imp:.4f}  {bar}")

    # ── export C++ header ─────────────────────────────────────────────────
    print(f"\nExporting C++ header to {args.out} ...")
    body_lines, classes = gbm_to_cpp(model, FEATURE_NAMES)

    n_trees = args.trees * len(classes)
    header = f"""\
//---------------------------------------------------------------------------
// heuristics/auto/difficulty_predictor.hpp
// https://github.com/HiPERACT-Scheduling/DLT-Studio
//
// ML difficulty predictor — auto-generated by tools/train_difficulty_predictor.py.
// DO NOT EDIT — regenerate by re-running the training script.
//
// A gradient-boosted ensemble ({args.trees} stages × {len(classes)} classes = {n_trees} trees,
// max depth {args.depth}) trained on {len(X)} labelled DLSInstance benchmarks.
// Predicts the difficulty tier of an instance for portfolio heuristics:
//   "easy"   — heuristic gap to exact < 1%
//   "medium" — gap 1–10%
//   "hard"   — gap > 10% or exact intractable (N large)
//
// Zero runtime dependency: the model is embedded as plain C++ arithmetic.
// Inference is O(depth × n_trees) — sub-microsecond.
//---------------------------------------------------------------------------

#ifndef DLS_HEURISTICS_AUTO_DIFFICULTY_PREDICTOR_HPP
#define DLS_HEURISTICS_AUTO_DIFFICULTY_PREDICTOR_HPP

#include <algorithm>
#include <array>
#include <string>

#include "core/instance_features.hpp"

namespace dls {{

class DifficultyPredictor {{
public:
    // Goal:   predict how hard this instance is for portfolio heuristics.
    // Input:  f - computed by computeFeatures(instance).
    // Output: "easy", "medium", or "hard".
    static std::string predict(const InstanceFeatures& features) {{
        const std::array<float, kDiffNumFeatures> f = {{{{
            static_cast<float>(features.N),
            static_cast<float>(features.memoryRatio),
            static_cast<float>(features.hasStartups),
            static_cast<float>(features.hasCommCost),
            static_cast<float>(features.heteroA),
            static_cast<float>(features.heteroC),
            static_cast<float>(features.heteroS),
            static_cast<float>(features.startupFraction),
            static_cast<float>(features.hasBeta),
            static_cast<float>(features.hasCost),
        }}}};
        double scores[kDiffNumClasses] = {{}};
        accumulate_diff_scores(f.data(), scores);
        const int best = static_cast<int>(
            std::max_element(scores, scores + kDiffNumClasses) - scores);
        return kDifficultyNames[best];
    }}

private:
"""

    footer = """\

};

}  // namespace dls

#endif  // DLS_HEURISTICS_AUTO_DIFFICULTY_PREDICTOR_HPP
"""

    with open(args.out, "w") as f:
        f.write(header)
        for line in body_lines:
            f.write("    " + line + "\n")
        f.write(footer)

    print(f"  Written: {args.out}")
    size_kb = os.path.getsize(args.out) / 1024
    print(f"  File size: {size_kb:.1f} KB")


if __name__ == "__main__":
    main()
