#!/usr/bin/env python3
"""
tools/train_makespan_predictor.py

Train a GBM regression model on log(makespan) from the solver-selector dataset
and export it as a self-contained C++ header.

The makespan predictor is used by MlSolver (heuristics/ml/ml_solver.hpp) to
estimate T* before constructing a schedule, enabling ML-vs-heuristic comparison.

Usage:
    python3 tools/train_makespan_predictor.py [--data tools/training_data.csv]
                                              [--out  lib/heuristics/ml/makespan_predictor.hpp]
                                              [--depth 6] [--trees 150]
"""

import argparse
import math
import os

import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.tree import _tree

FEATURE_NAMES = ["N", "memoryRatio", "hasStartups", "hasCommCost",
                 "heteroA", "heteroC", "heteroS", "startupFraction",
                 "hasBeta", "hasCost",
                 "meanA", "meanC", "meanS", "speedupA", "speedupC", "loadPerProc"]


# ── CSV load ───────────────────────────────────────────────────────────────

def load_data(path):
    import csv
    X, y = [], []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if "best_makespan" not in row or not row["best_makespan"]:
                continue
            ms = float(row["best_makespan"])
            if ms <= 0:
                continue
            feats = [float(row[n]) for n in FEATURE_NAMES]
            X.append(feats)
            y.append(math.log(ms))
    return np.array(X), np.array(y)


# ── export GBM regressor as C++ ───────────────────────────────────────────

def gbm_regressor_to_cpp(model, feature_names):
    lines = []
    lines.append("// Auto-generated by tools/train_makespan_predictor.py — do not edit.")
    lines.append(f"// GBM regressor: {len(model.estimators_)} stages, "
                 f"max_depth={model.max_depth}, predicts log(T*).")
    lines.append(f"// Feature order: {', '.join(feature_names)}")
    lines.append("")
    lines.append(f"static constexpr int kMsNumFeatures = {len(feature_names)};")
    lines.append("")
    lines.append("static double predict_log_makespan(const float* f) {")
    lines.append(f"    double score = {model.init_.constant_[0][0]:.10f};")
    lines.append(f"    const double lr = {model.learning_rate:.10f};")

    for stage_i, stage in enumerate(model.estimators_):
        t = stage[0].tree_  # regressor has one tree per stage
        lines.append(f"    // stage {stage_i}")

        def recurse(node, depth):
            pad = "    " * (depth + 1)
            if t.feature[node] != _tree.TREE_UNDEFINED:
                fi  = t.feature[node]
                thr = t.threshold[node]
                lines.append(f"{pad}{{")
                lines.append(f"{pad}    if (f[{fi}] <= {thr:.10f}f) {{")
                recurse(t.children_left[node],  depth + 2)
                lines.append(f"{pad}    }} else {{")
                recurse(t.children_right[node], depth + 2)
                lines.append(f"{pad}    }}")
                lines.append(f"{pad}}}")
            else:
                val = t.value[node][0][0]
                lines.append(f"{pad}score += lr * {val:.10f};")

        recurse(0, 0)

    lines.append("    return score;")
    lines.append("}")
    return lines


# ── main ──────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data",  default=os.path.join(os.path.dirname(__file__), "training_data.csv"))
    ap.add_argument("--out",   default=os.path.join(os.path.dirname(__file__),
                                                     "..", "lib", "heuristics", "ml",
                                                     "makespan_predictor.hpp"))
    ap.add_argument("--depth", type=int, default=6)
    ap.add_argument("--trees", type=int, default=150)
    ap.add_argument("--seed",  type=int, default=0)
    args = ap.parse_args()

    print(f"Loading {args.data} ...")
    X, y = load_data(args.data)
    print(f"  {len(X)} samples with makespan labels")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.15, random_state=args.seed)

    print(f"Training GBM regressor (depth={args.depth}, trees={args.trees}) ...")
    model = GradientBoostingRegressor(
        n_estimators=args.trees,
        max_depth=args.depth,
        learning_rate=0.1,
        subsample=0.8,
        random_state=args.seed,
        verbose=0,
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    mape   = mean_absolute_percentage_error(np.exp(y_test), np.exp(y_pred))
    print(f"  Test MAPE on exp(log T): {mape*100:.2f}%")

    cv = cross_val_score(model, X, y, cv=5, scoring="r2")
    print(f"  5-fold CV R²: {cv.mean():.3f} ± {cv.std():.3f}")

    print("\nFeature importances:")
    for name, imp in sorted(zip(FEATURE_NAMES, model.feature_importances_),
                            key=lambda x: -x[1]):
        bar = "█" * int(imp * 40)
        print(f"  {name:20s} {imp:.4f}  {bar}")

    print(f"\nExporting C++ header to {args.out} ...")
    body = gbm_regressor_to_cpp(model, FEATURE_NAMES)

    header = f"""\
//---------------------------------------------------------------------------
// heuristics/ml/makespan_predictor.hpp
// https://github.com/HiPERACT-Scheduling/DLT-Studio
//
// ML makespan predictor — auto-generated by tools/train_makespan_predictor.py.
// DO NOT EDIT — regenerate by re-running the training script.
//
// GBM regressor ({args.trees} stages, max_depth {args.depth}) trained on
// {len(X)} single-load DLSInstance benchmarks. Predicts log(T*); caller takes
// exp() to recover T. Test MAPE: {mape*100:.1f}%.
//
// Zero runtime dependency: the model is embedded as plain C++ arithmetic.
//---------------------------------------------------------------------------

#ifndef DLS_HEURISTICS_ML_MAKESPAN_PREDICTOR_HPP
#define DLS_HEURISTICS_ML_MAKESPAN_PREDICTOR_HPP

#include <array>
#include <cmath>
#include <string>

#include "core/instance_features.hpp"

namespace dls {{

class MakespanPredictor {{
public:
    // Goal:   predict log(T*) for a single-load DLS instance.
    // Input:  f - computed by computeFeatures(instance).
    // Output: log(predicted makespan); caller takes exp() to recover T.
    static double predict(const InstanceFeatures& features) {{
        const std::array<float, kMsNumFeatures> fa = {{{{
            static_cast<float>(features.N),
            static_cast<float>(features.memoryRatio),
            static_cast<float>(features.hasStartups),
            static_cast<float>(features.hasCommCost),
            static_cast<float>(features.heteroA),
            static_cast<float>(features.heteroC),
            static_cast<float>(features.heteroS),
            static_cast<float>(features.startupFraction),
            static_cast<float>(features.hasBeta),
            static_cast<float>(features.hasCost),
            static_cast<float>(features.meanA),
            static_cast<float>(features.meanC),
            static_cast<float>(features.meanS),
            static_cast<float>(features.speedupA),
            static_cast<float>(features.speedupC),
            static_cast<float>(features.loadPerProc),
        }}}};
        const float* f = fa.data();
        return predict_log_makespan(f);
    }}

private:
"""

    footer = """\

};

}  // namespace dls

#endif  // DLS_HEURISTICS_ML_MAKESPAN_PREDICTOR_HPP
"""

    with open(args.out, "w") as f:
        f.write(header)
        for line in body:
            f.write("    " + line + "\n")
        f.write(footer)

    print(f"  Written: {args.out}  ({os.path.getsize(args.out)//1024} KB)")


if __name__ == "__main__":
    main()
