#!/usr/bin/env python3
"""
tools/train_energy_predictor.py

Train a GBM regression model on log(minimum energy) from the energy training
dataset (generate_energy_training_data.py) and export it as a self-contained,
zero-dependency C++ header.

The dataset's labels are exact (HiGHS MIP, mipGap=0), so this is a surrogate for
the true minimum achievable energy of an instance — a quantity with no closed
form once processors are heterogeneous.

Feature columns are auto-detected from the CSV header (everything except the
label and provenance columns). The exported header exposes a standalone
`predict_log_energy(const float* f)` taking the features in the documented
order — no feature struct dependency, so a future energy-aware solver can adopt
it by filling a float array.

Usage:
    python3 tools/train_energy_predictor.py [--depth 6] [--trees 150]
"""

import argparse
import csv
import math
import os

import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.tree import _tree

LABEL       = "energy"
NON_FEATURE = {LABEL, "makespan", "seed", "regime", "oracle", "label_is_exact", "solver_wall_ms"}


def load_data(path):
    with open(path) as f:
        reader = csv.DictReader(f)
        feature_names = [c for c in reader.fieldnames if c not in NON_FEATURE]
        X, y = [], []
        for row in reader:
            e = float(row[LABEL])
            if e <= 0:
                continue
            X.append([float(row[n]) for n in feature_names])
            y.append(math.log(e))
    return np.array(X), np.array(y), feature_names


def gbm_regressor_to_cpp(model):
    lines = [f"    double score = {model.init_.constant_[0][0]:.10f};",
             f"    const double lr = {model.learning_rate:.10f};"]
    for stage_i, stage in enumerate(model.estimators_):
        t = stage[0].tree_
        lines.append(f"    // stage {stage_i}")

        def recurse(node, depth):
            pad = "    " * (depth + 1)
            if t.feature[node] != _tree.TREE_UNDEFINED:
                fi, thr = t.feature[node], t.threshold[node]
                lines.append(f"{pad}if (f[{fi}] <= {thr:.10f}f) {{")
                recurse(t.children_left[node],  depth + 1)
                lines.append(f"{pad}}} else {{")
                recurse(t.children_right[node], depth + 1)
                lines.append(f"{pad}}}")
            else:
                lines.append(f"{pad}score += lr * {t.value[node][0][0]:.10f};")

        recurse(0, 1)
    lines.append("    return score;")
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data",  default=os.path.join(os.path.dirname(__file__),
                                                     "energy_training_data.csv"))
    ap.add_argument("--out",   default=os.path.join(os.path.dirname(__file__),
                                                     "..", "lib", "heuristics", "ml",
                                                     "energy_predictor.hpp"))
    ap.add_argument("--depth", type=int, default=6)
    ap.add_argument("--trees", type=int, default=150)
    ap.add_argument("--seed",  type=int, default=0)
    args = ap.parse_args()

    print(f"Loading {args.data} ...")
    X, y, feature_names = load_data(args.data)
    print(f"  {len(X)} energy samples, {len(feature_names)} features: {feature_names}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.15, random_state=args.seed)

    print(f"Training GBM regressor (depth={args.depth}, trees={args.trees}) ...")
    model = GradientBoostingRegressor(
        n_estimators=args.trees, max_depth=args.depth, learning_rate=0.1,
        subsample=0.8, random_state=args.seed)
    model.fit(X_train, y_train)

    mape = mean_absolute_percentage_error(np.exp(y_test), np.exp(model.predict(X_test)))
    cv   = cross_val_score(model, X, y, cv=5, scoring="r2")
    print(f"  Test MAPE on energy: {mape*100:.2f}%")
    print(f"  5-fold CV R²: {cv.mean():.3f} ± {cv.std():.3f}")
    print("\nFeature importances:")
    for name, imp in sorted(zip(feature_names, model.feature_importances_), key=lambda x: -x[1]):
        print(f"  {name:24s} {imp:.4f}  {'█' * int(imp * 40)}")

    body = gbm_regressor_to_cpp(model)
    print(f"\nExporting C++ header to {args.out} ...")
    header = f"""\
//---------------------------------------------------------------------------
// heuristics/ml/energy_predictor.hpp
// https://github.com/HiPERACT-Scheduling/DLT-Studio
//
// ML minimum-energy predictor — auto-generated by tools/train_energy_predictor.py.
// DO NOT EDIT — regenerate via the script.
//
// GBM regressor ({args.trees} stages, max_depth {args.depth}) trained on {len(X)}
// exact (HiGHS MILP, minimizeCost) single-installment energy-model benchmarks.
// Predicts log(minimum energy); caller takes exp(). Test MAPE: {mape*100:.1f}%.
// Zero runtime dependency (plain C++ arithmetic).
//
// Standalone: pass the {len(feature_names)} features as a float array in this order —
//   {', '.join(feature_names)}
//---------------------------------------------------------------------------

#ifndef DLS_HEURISTICS_ML_ENERGY_PREDICTOR_HPP
#define DLS_HEURISTICS_ML_ENERGY_PREDICTOR_HPP

namespace dls {{

static constexpr int kEnergyNumFeatures = {len(feature_names)};

// Goal:   predict log(minimum energy) for an energy-model instance.
// Input:  f - the {len(feature_names)} features in the documented order.
// Output: log(minimum energy); caller takes exp() to recover the energy.
static inline double predict_log_energy(const float* f) {{
"""
    with open(args.out, "w") as fh:
        fh.write(header)
        for line in body:
            fh.write(line + "\n")
        fh.write("}\n\n}  // namespace dls\n\n#endif  // DLS_HEURISTICS_ML_ENERGY_PREDICTOR_HPP\n")
    print(f"  Written: {args.out}  ({os.path.getsize(args.out)//1024} KB)")


if __name__ == "__main__":
    main()
