#!/usr/bin/env python3
"""
tools/train_mlsd_predictor.py

Train a GBM regression model on log(Cmax) from the MLSD training dataset
and export it as a self-contained C++ header.

The predictor is used by MlMlsdSolver (heuristics/ml/ml_mlsd_solver.hpp) to
estimate the optimal Cmax for MLSD instances before scheduling.

Usage:
    python3 tools/train_mlsd_predictor.py [--data tools/mlsd_training_data.csv]
                                          [--out  lib/heuristics/ml/mlsd_predictor.hpp]
                                          [--depth 6] [--trees 150]
"""

import argparse
import math
import os

import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.tree import _tree

FEATURE_NAMES = ["nTasks", "nProcs", "meanV", "cvV", "maxMinV", "totalLoadPerProc",
                 "memoryRatio", "meanA", "heteroA", "speedupA", "hasStartups", "hasCommCost"]


# ── CSV load ───────────────────────────────────────────────────────────────

def load_data(path):
    import csv
    X, y = [], []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            cmax = float(row["cmax"])
            if cmax <= 0:
                continue
            feats = [float(row[n]) for n in FEATURE_NAMES]
            X.append(feats)
            y.append(math.log(cmax))
    return np.array(X), np.array(y)


# ── export GBM regressor as C++ ───────────────────────────────────────────

def gbm_regressor_to_cpp(model, feature_names):
    lines = []
    lines.append("// Auto-generated by tools/train_mlsd_predictor.py — do not edit.")
    lines.append(f"// GBM regressor: {len(model.estimators_)} stages, "
                 f"max_depth={model.max_depth}, predicts log(Cmax*).")
    lines.append(f"// Feature order: {', '.join(feature_names)}")
    lines.append("")
    lines.append(f"static constexpr int kMlsdNumFeatures = {len(feature_names)};")
    lines.append("")
    lines.append("static double predict_log_cmax(const float* f) {")
    lines.append(f"    double score = {model.init_.constant_[0][0]:.10f};")
    lines.append(f"    const double lr = {model.learning_rate:.10f};")

    for stage_i, stage in enumerate(model.estimators_):
        t = stage[0].tree_
        lines.append(f"    // stage {stage_i}")

        def recurse(node, depth):
            pad = "    " * (depth + 1)
            if t.feature[node] != _tree.TREE_UNDEFINED:
                fi  = t.feature[node]
                thr = t.threshold[node]
                lines.append(f"{pad}{{")
                lines.append(f"{pad}    if (f[{fi}] <= {thr:.10f}f) {{")
                recurse(t.children_left[node],  depth + 2)
                lines.append(f"{pad}    }} else {{")
                recurse(t.children_right[node], depth + 2)
                lines.append(f"{pad}    }}")
                lines.append(f"{pad}}}")
            else:
                val = t.value[node][0][0]
                lines.append(f"{pad}score += lr * {val:.10f};")

        recurse(0, 0)

    lines.append("    return score;")
    lines.append("}")
    return lines


# ── main ──────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data",  default=os.path.join(os.path.dirname(__file__),
                                                     "mlsd_training_data.csv"))
    ap.add_argument("--out",   default=os.path.join(os.path.dirname(__file__),
                                                     "..", "lib", "heuristics", "ml",
                                                     "mlsd_predictor.hpp"))
    ap.add_argument("--depth", type=int, default=6)
    ap.add_argument("--trees", type=int, default=150)
    ap.add_argument("--seed",  type=int, default=0)
    args = ap.parse_args()

    print(f"Loading {args.data} ...")
    X, y = load_data(args.data)
    print(f"  {len(X)} MLSD samples")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.15, random_state=args.seed)

    print(f"Training GBM regressor (depth={args.depth}, trees={args.trees}) ...")
    model = GradientBoostingRegressor(
        n_estimators=args.trees,
        max_depth=args.depth,
        learning_rate=0.1,
        subsample=0.8,
        random_state=args.seed,
        verbose=0,
    )
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    mape   = mean_absolute_percentage_error(np.exp(y_test), np.exp(y_pred))
    print(f"  Test MAPE on exp(log Cmax): {mape*100:.2f}%")

    cv = cross_val_score(model, X, y, cv=5, scoring="r2")
    print(f"  5-fold CV R²: {cv.mean():.3f} ± {cv.std():.3f}")

    print("\nFeature importances:")
    for name, imp in sorted(zip(FEATURE_NAMES, model.feature_importances_),
                            key=lambda x: -x[1]):
        bar = "█" * int(imp * 40)
        print(f"  {name:20s} {imp:.4f}  {bar}")

    print(f"\nExporting C++ header to {args.out} ...")
    body = gbm_regressor_to_cpp(model, FEATURE_NAMES)

    header = f"""\
//---------------------------------------------------------------------------
// heuristics/ml/mlsd_predictor.hpp
// https://github.com/HiPERACT-Scheduling/DLT-Studio
//
// ML MLSD Cmax predictor — auto-generated by tools/train_mlsd_predictor.py.
// DO NOT EDIT — regenerate by re-running the training script.
//
// GBM regressor ({args.trees} stages, max_depth {args.depth}) trained on
// {len(X)} MLSD instance benchmarks. Predicts log(Cmax*); caller takes
// exp() to recover Cmax. Test MAPE: {mape*100:.1f}%.
//
// Zero runtime dependency: the model is embedded as plain C++ arithmetic.
//---------------------------------------------------------------------------

#ifndef DLS_HEURISTICS_ML_MLSD_PREDICTOR_HPP
#define DLS_HEURISTICS_ML_MLSD_PREDICTOR_HPP

#include <array>
#include <cmath>
#include <string>

#include "mlsd/mlsd_instance_features.hpp"

namespace dls {{

class MlsdPredictor {{
public:
    // Goal:   predict log(Cmax*) for an MLSD instance.
    // Input:  f - computed by computeMlsdFeatures(instance).
    // Output: log(predicted Cmax); caller takes exp() to recover Cmax.
    static double predict(const MlsdInstanceFeatures& features) {{
        const std::array<float, kMlsdNumFeatures> fa = {{{{
            static_cast<float>(features.nTasks),
            static_cast<float>(features.nProcs),
            static_cast<float>(features.meanV),
            static_cast<float>(features.cvV),
            static_cast<float>(features.maxMinV),
            static_cast<float>(features.totalLoadPerProc),
            static_cast<float>(features.memoryRatio),
            static_cast<float>(features.meanA),
            static_cast<float>(features.heteroA),
            static_cast<float>(features.speedupA),
            static_cast<float>(features.hasStartups),
            static_cast<float>(features.hasCommCost),
        }}}};
        const float* f = fa.data();
        return predict_log_cmax(f);
    }}

private:
"""

    footer = """\

};

}  // namespace dls

#endif  // DLS_HEURISTICS_ML_MLSD_PREDICTOR_HPP
"""

    with open(args.out, "w") as f:
        f.write(header)
        for line in body:
            f.write("    " + line + "\n")
        f.write(footer)

    print(f"  Written: {args.out}  ({os.path.getsize(args.out)//1024} KB)")


if __name__ == "__main__":
    main()
